version: '3'

services:
  ui:
    build: ./ui
    restart: on-failure
    volumes:
      - ./ui:/app
    ports:
      - 3000:3000
    depends_on:
      - api
    environment:
      REACT_APP_API_URL: http://localhost:5000
      PORT: 3000

  api:
    build: ./api
    restart: on-failure
    volumes:
      - ./api:/app
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      DB_CONNECTION_STRING: mongodb://db/Tododb
      PORT: 5000

  db:
    image: mongo:latest
    restart: always
